Add set -e to fail if any step fails
This will prevent the build from continuing if one of the steps fails,
ensuring that the output from CodeBuild is accurate about success or
failure

diff --git a/cloudy_mozdef/ci/deploy b/cloudy_mozdef/ci/deploy
--- a/cloudy_mozdef/ci/deploy
+++ b/cloudy_mozdef/ci/deploy
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e  # Exit immediately if a command exits with a non-zero status.
+
 echo 'Welcome github webhook to the CodeBuild Job of MozDef.'
 echo "It's dangerous to go alone.  Take one of these: <%%%%|==========>"
 
